const TARGETS={low:3.9,high:10};
const AVG_TARGETS={low:4.4,high:10};
const averageRanges={
  '7':{label:'2026.08.27 – 2026.09.02',valid:'有效 7/7 天',summary:{tir:86,tar:6,tbr:8,avg:'6.4',days:'7/7'},values:[5.8,4.2,5.9,6.8,10.2,6.6,6.4],dates:['08/27','08/28','08/29','08/30','08/31','09/01','09/02'],volatility:[2.5,2.2,3.4,2.8,3.1,2.6,2.4]},
  '14':{label:'2026.08.20 – 2026.09.02',valid:'有效 14/14 天',summary:{tir:84,tar:7,tbr:9,avg:'6.3',days:'14/14'},values:[5.8,6.2,4.1,6.7,6.1,7.0,6.4,6.8,6.0,10.4,6.6,6.3,6.9,6.5],dates:['08/20','08/21','08/22','08/23','08/24','08/25','08/26','08/27','08/28','08/29','08/30','08/31','09/01','09/02'],volatility:[2.4,2.8,2.1,3.6,2.5,4.1,2.7,3.0,2.2,5.4,2.9,2.5,3.3,2.4]},
  custom:{label:'2026.08.24 – 2026.09.02',valid:'有效 10/10 天',summary:{tir:82,tar:8,tbr:10,avg:'6.5',days:'10/10'},values:[6.1,4.1,6.8,6.4,10.4,6.0,7.1,6.5,6.9,6.6],dates:['08/24','08/25','08/26','08/27','08/28','08/29','08/30','08/31','09/01','09/02'],volatility:[2.5,4.1,2.7,3.0,2.2,5.4,2.9,2.5,3.3,2.4]}
};
const series={
  realtime:[5.1,5.0,5.2,5.5,5.8,5.7,5.4,5.2,5.0,4.8,4.9,5.3,5.7,6.1,6.4,6.2,5.9,5.6,5.8,6.2,6.7,7.1,7.0,6.6,6.2,6.0,6.3,6.8,7.4,7.9,8.2,7.8,7.3,6.9,6.7,6.5,6.6,6.9,7.2,7.0,6.7,6.4,6.2,6.3,6.7,7.1,7.4,7.2,6.9],
  day:[3.7,3.6,3.4,3.2,3.1,3.3,3.6,3.8,4.2,4.0,4.3,4.8,5.5,6.1,6.8,7.5,8.1,8.7,9.4,10.1,10.4,10.0,9.3,8.5,7.9,7.4,7.1,6.9,6.8,7.0,7.3,7.6,7.8,7.6,7.3,6.9,6.5,6.2,6.0,5.8,5.7,5.9,6.2,6.5,6.8,7.0,6.8,6.4,6.0]
};
function pointXY(v,i,n){return{x:10+320*i/(n-1),y:132-(Math.max(2,Math.min(14,v))-2)/12*118}}
function stateColor(v){return v<TARGETS.low?'#d82c35':v>TARGETS.high?'#ed9b00':'#34383c'}
function stats(a){const n=a.length,low=a.filter(v=>v<TARGETS.low).length,high=a.filter(v=>v>TARGETS.high).length;return{tir:Math.round((n-low-high)/n*100),tbr:Math.round(low/n*100),tar:Math.round(high/n*100),avg:(a.reduce((s,v)=>s+v,0)/n).toFixed(1),max:Math.max(...a).toFixed(1),min:Math.min(...a).toFixed(1),range:(Math.max(...a)-Math.min(...a)).toFixed(1)}}
function thresholdLegend(){return `<div class="chart-legend threshold-legend"><span><i class="legend-swatch low"></i>&lt;${TARGETS.low}</span><span><i class="legend-swatch high"></i>&gt;${TARGETS.high.toFixed(1)}</span></div>`}
function chart(type){const a=series[type]||series.day,segments=a.slice(0,-1).map((v,i)=>{const p=pointXY(v,i,a.length),q=pointXY(a[i+1],i+1,a.length),c=stateColor((v+a[i+1])/2);return `<line class="chart-segment" x1="${p.x.toFixed(1)}" y1="${p.y.toFixed(1)}" x2="${q.x.toFixed(1)}" y2="${q.y.toFixed(1)}" stroke="${c}"/>`}).join('');return `<svg class="chart" viewBox="0 0 340 170" role="img" aria-label="血糖曲线"><rect class="band" x="0" y="53" width="340" height="79" rx="3"/><line class="grid" x1="0" y1="14" x2="340" y2="14"/><line class="grid" x1="0" y1="53" x2="340" y2="53"/><line class="grid" x1="0" y1="92" x2="340" y2="92"/><line class="grid" x1="0" y1="132" x2="340" y2="132"/>${segments}<text x="4" y="18">14.0</text><text x="4" y="57">${TARGETS.high.toFixed(1)}</text><text x="4" y="96">6.0</text><text x="4" y="136">${TARGETS.low.toFixed(1)}</text><text x="8" y="153">00:00</text><text x="105" y="153">06:00</text><text x="205" y="153">12:00</text><text x="295" y="153">18:00</text></svg>${thresholdLegend()}`}
function averageColor(v){return v<AVG_TARGETS.low?'#d82c35':v>AVG_TARGETS.high?'#ed9b00':'#19b99f'}
function rangeKey(value){return averageRanges[value]?value:'14'}
function averageAxisDates(d){const picks=d.length<=7?[0,Math.floor((d.length-1)/2),d.length-1]:[0,Math.floor((d.length-1)/3),Math.floor((d.length-1)*2/3),d.length-1];return picks.map(i=>({i,label:d[i]}))}
function multiDayChart(range='14'){const m=averageRanges[rangeKey(range)],a=m.values,d=m.dates,gap=Math.min(23,(318/a.length)-2),bars=a.map((v,i)=>{const h=Math.max(10,(v/12)*78),x=11+i*(318/a.length)+(gap/2);return `<rect x="${x.toFixed(1)}" y="${(112-h).toFixed(1)}" width="${gap.toFixed(1)}" height="${h.toFixed(1)}" rx="4" fill="${averageColor(v)}"><title>${d[i]} 每日平均血糖 ${v.toFixed(1)} mmol/L</title></rect><text x="${(x+gap/2).toFixed(1)}" y="${(108-h).toFixed(1)}" text-anchor="middle">${v.toFixed(1)}</text>`}).join(''),axis=averageAxisDates(d).map(x=>`<text x="${(11+x.i*(318/a.length)+(gap/2)).toFixed(1)}" y="134" text-anchor="middle">${x.label}</text>`).join('');return `<div class="daily-average-block" data-daily-average="${rangeKey(range)}"><div class="card-title">每日平均血糖 <small>每根柱子 = 当天平均值</small></div><svg class="chart" viewBox="0 0 340 150" role="img" aria-label="${m.label}每日平均血糖"><line class="grid" x1="14" y1="34" x2="330" y2="34"/><line class="grid" x1="14" y1="73" x2="330" y2="73"/><line class="grid" x1="14" y1="112" x2="330" y2="112"/>${bars}<text x="4" y="38">12</text><text x="4" y="77">6</text><text x="4" y="116">0</text>${axis}</svg><div class="chart-legend average-legend"><span><i class="legend-dot" style="background:#d82c35"></i>&lt;${AVG_TARGETS.low.toFixed(1)}</span><span><i class="legend-dot" style="background:#19b99f"></i>${AVG_TARGETS.low.toFixed(1)}–${AVG_TARGETS.high.toFixed(1)}</span><span><i class="legend-dot" style="background:#ed9b00"></i>&gt;${AVG_TARGETS.high.toFixed(1)}</span></div></div>`}
function dailyBars(range='14'){const m=averageRanges[rangeKey(range)],a=m.volatility,d=m.dates;return `<div class="daily-volatility-bars" style="height:110px;display:flex;align-items:end;gap:7px;padding:18px 8px 2px;border-bottom:1px solid #dfe9e6">${a.map((v,i)=>`<div style="flex:1;height:${Math.round(30+v*12)}px;background:#7ac9ba;border-radius:6px 6px 0 0;position:relative" title="${d[i]} 最大波动 ${v.toFixed(1)} mmol/L"><small style="position:absolute;top:-17px;left:50%;transform:translateX(-50%);font-size:10px;color:#778;white-space:nowrap">${v.toFixed(1)}</small></div>`).join('')}</div><div class="coverage"><span>${d[0]}　　 ${d[Math.floor((d.length-1)/2)]}　　 ${d[d.length-1]}</span><b>mmol/L</b></div>`}
function multiDayOverlay(){const dates=['08/23','08/27','09/01'],colors=['#19b99f','#efaa28','#7084d8'],sets=[[5.1,5.4,5.0,5.6,5.3,5.8,6.2,5.7,5.4,5.9,6.1,5.8],[5.4,5.2,5.6,5.1,5.5,6.0,5.7,6.2,5.9,6.1,6.4,6.0],[5.2,5.5,5.3,5.8,5.6,5.9,6.3,5.8,5.7,6.0,6.2,6.1]],lines=sets.map((a,k)=>`<polyline fill="none" stroke="${colors[k]}" stroke-width="2" points="${a.map((v,i)=>{const p=pointXY(v,i,a.length);return `${p.x.toFixed(1)},${(p.y-2).toFixed(1)}`}).join(' ')}"><title>${dates[k]} 多日血糖曲线</title></polyline>`).join('');return `<svg class="chart" viewBox="0 0 340 170" role="img" aria-label="近14天多日血糖曲线叠加"><rect class="band" x="0" y="53" width="340" height="79" rx="3"/><line class="grid" x1="0" y1="14" x2="340" y2="14"/><line class="grid" x1="0" y1="53" x2="340" y2="53"/><line class="grid" x1="0" y1="92" x2="340" y2="92"/><line class="grid" x1="0" y1="132" x2="340" y2="132"/>${lines}<text x="4" y="18">14.0</text><text x="4" y="57">${TARGETS.high.toFixed(1)}</text><text x="4" y="96">6.0</text><text x="4" y="136">${TARGETS.low.toFixed(1)}</text><text x="8" y="153">00:00</text><text x="105" y="153">06:00</text><text x="205" y="153">12:00</text><text x="295" y="153">18:00</text></svg><div class="chart-legend overlay-legend">${dates.map((d,i)=>`<span><i class="legend-dot" style="background:${colors[i]}"></i>${d}</span>`).join('')}</div>`}
const chartWithColumnCaption=multiDayChart;multiDayChart=(range='14')=>chartWithColumnCaption(range).replace('<small>每根柱子 = 当天平均值</small>','');
const note=(title,body,sections)=>({title,body,sections});
const screens={
 overview:{title:'第一版可演示方案',sub:'糖哨兵血糖中心 · 家庭照护优先 · P0 先行，候选模块可拖拽',notes:note('本轮方案判断','第一版先建立“实时查看 → 单日定位 → 多日发现规律”的基础链路。外部 CGM 只提供血糖值和时间戳；饮食、运动、睡眠、用药、胰岛素等事件由糖哨兵 App 记录后再关联。',[['家庭照护主线','本期按单一当前使用者展示，先查看当前状态与连续血糖变化；多照护对象和对象切换时机待后续产品决策。'],['范围边界','Gluroo 的闭环、剂量计算不纳入一期；AI 解释、完整报告、饮食对比先放候选区。'],['本版时间口径','实时曲线采用 6 / 12 / 24 小时；分析中心采用日、近 7 天、近 14 天、自定义。']]),content:`<div class="title-row"><div><div class="eyebrow">糖哨兵 · BLOOD GLUCOSE CENTER</div><h2 class="title">先让照护者看懂“现在”和“规律”</h2><p class="subtitle">第一版以血糖值 + 时间戳为底座，逐步接入糖哨兵记录的照护事件。</p></div><span class="tag">P0 可演示</span></div><div class="flow"><div class="flow-card"><span class="tag">01 · 实时</span><b>血糖 Tab</b><p>当前血糖、趋势箭头、更新时间、数据状态，快速查看当前血糖状态。</p></div><div class="flow-card"><span class="tag">02 · 定位</span><b>单日分析</b><p>回看某一天，找到高低血糖发生的时间和当天整体指标。</p></div><div class="flow-card"><span class="tag">03 · 发现</span><b>多日趋势</b><p>比较 7/14 天，发现相似时段是否反复出现问题。</p></div></div><div class="priority-grid"><div class="priority"><h3>P0 · 本版先做</h3><ul><li>实时曲线：6/12/24 小时</li><li>单日曲线与日期切换</li><li>日/周/14 天/自定义范围</li><li>TIR/TAR/TBR、平均/最高/最低/最大波动</li><li>覆盖天数、延迟、中断、数据不足</li></ul></div><div class="priority"><h3>候选 · 可拖拽</h3><ul><li>多日曲线叠加、日均趋势</li><li>AGP、CV、GMI</li><li>夜间分析、事件分布</li><li>周报、AI 解释、照护摘要</li><li>饮食/运动/胰岛素关联</li></ul></div></div>`},
realtime:{title:'血糖 Tab｜实时监测',sub:'P0 · 单一当前使用者的第一眼状态查看',notes:note('页面逻辑','按单一当前使用者展示。当前值、趋势箭头、更新时间和状态必须同一数据快照生成。',[['时间选择决策','本版采用 6/12/24 小时。3/6/12/24（硅基）、4/8/12/24（三诺）、6/12/24（微泰）、4/12/24（糖动）作为竞品参考，不直接照搬。'],['状态','目标范围内、偏高、偏低、数据延迟、数据中断。']]),content:`<div class="eyebrow">P0 · 实时监测</div><h2 class="title">林小满的血糖</h2><p class="subtitle">当前使用者视角：先看当前状态，再决定是否进入分析。</p><div class="phone"><div class="phone-top"><h2>林小满 <small>⌄</small></h2><small>外部 CGM · 3分钟前</small><div class="current"><div><strong>5.8</strong><span>mmol/L</span></div><div class="arrow">→</div></div><div class="status">目标范围内</div></div><div class="phone-card"><div class="card-title">最近血糖曲线</div><div class="segmented"><button>6 小时</button><button>12 小时</button><button class="active">24 小时</button></div>${chart('realtime')}</div><div class="phone-card"><div class="card-title">今日摘要 <small>截至 16:25</small></div><div class="stat-grid"><div class="stat"><b>92%</b><span>目标范围内</span></div><div class="stat"><b>5.6</b><span>平均血糖</span></div><div class="stat"><b>0</b><span>高低事件</span></div></div><div class="coverage"><span>数据覆盖</span><b>23 小时 40 分</b></div></div></div>`},
analysis:{title:'分析中心｜单日分析',sub:'P0 · 回看某一天，定位异常发生在哪里',notes:note('页面逻辑','单日分析不依赖饮食或运动记录也能完整使用。曲线是主视图，指标是快速摘要；点击曲线区域，可查看时间、血糖值和数据来源。',[['核心指标','TIR/目标范围内时间、TAR、TBR、平均血糖、最高/最低血糖及时间、最大波动。CV/GMI先放候选区。'],['统一口径','同一日期、目标范围、数据截止时间、数据源和舍入规则下，五段式“目标范围内”必须与 TIR 完全一致。'],['异常交互','点击高/低区域显示发生时段；不提供诊断或用药调整建议。']]),content:`<div class="eyebrow">P0 · 分析中心</div><h2 class="title">2026 年 09 月 02 日</h2><p class="subtitle">林小满 · 数据覆盖 23 小时 40 分 · 点击曲线区域查看时间和值</p><div class="phone"><div class="phone-card" style="margin-top:0"><div class="card-title">单日血糖曲线</div>${chart('day')}<div class="coverage"><span>00:00　　06:00　　12:00　　18:00　　24:00</span><b>有效覆盖 23 小时 40 分</b></div></div><div class="phone-card"><div class="card-title">当天表现 <small>ⓘ</small></div><div class="stat-grid"><div class="stat"><b>88%</b><span>目标范围内 TIR</span></div><div class="stat"><b>6.1</b><span>平均血糖</span></div><div class="stat"><b>2.4</b><span>最大波动</span></div></div><div class="stat-grid" style="margin-top:8px"><div class="stat"><b>9.8</b><span>最高 · 13:20</span></div><div class="stat"><b>3.7</b><span>最低 · 03:45</span></div><div class="stat"><b>12%</b><span>低于目标 TBR</span></div></div></div><div class="phone-card"><div class="card-title">已记录事件 <small>由糖哨兵 App 记录</small></div><div class="coverage"><span>暂无饮食/运动/用药记录</span><b>去记录 ＋</b></div></div></div>`},
 trend:{title:'分析中心｜多日分析',sub:'P0 · 用 7/14 天视角发现重复规律',notes:note('页面逻辑','多日分析是单日分析的上一级入口。默认近 14 天，照护者可以切到近 7 天或自定义；点击某一天进入同一套单日分析页面。AGP 与周期指标、多日趋势同属本页，不独立成页。',[['本版展示','时间范围、有效天数、TIR/TAR/TBR、平均血糖、AGP、多日趋势和进入单日分析的路径。'],['AGP 数据口径','AGP 与当前周期数据使用同一组示意数据；数据不足时不绘制图谱，只显示不可用状态。'],['家庭照护价值','从不同日期中归纳相似时段的重复波动，先判断问题是否持续，再下钻到具体某一天。']]),content:`<div class="eyebrow">P0 · 分析中心</div><h2 class="title">多日分析</h2><p class="subtitle">观察问题是偶发，还是在相似时段重复发生。</p><div class="phone"><div class="phone-card" style="margin-top:0"><div class="segmented trend-range-switch"><button data-range="7">近 7 天</button><button data-range="14" class="active">近 14 天</button><button data-range="custom">自定义</button></div><div class="coverage trend-range-summary"><span>2026.08.20 – 2026.09.02</span><b>有效 14/14 天</b></div>${multiDayChart('14')}</div><div class="phone-card trend-cycle-summary"><div class="card-title">周期摘要</div><div class="stat-grid"><div class="stat"><b>84%</b><span>目标范围内 TIR</span></div><div class="stat"><b>6.3</b><span>平均血糖</span></div><div class="stat"><b>14/14</b><span>有效天数</span></div></div></div><div class="phone-card"><div class="card-title">每日最大波动 <small>当天最高值 − 最低值</small></div><div class="daily-volatility-block">${dailyBars('14')}</div></div></div>`},
 candidates:{title:'候选模块板',sub:'P1 / P1.5 / P2 · 可拖拽进页面，不默认全部纳入第一版',notes:note('拖拽规则','候选模块用于评审时快速组合，不代表已经确认进入开发。每个模块先看它是否提升家庭照护判断，再决定放入实时页、分析页或独立报告。',[['建议先拖入的增强项','多日曲线叠加、时段/夜间分析、AGP。'],['暂缓的复杂项','AI 解释、饮食对比、个性化报告、照护摘要。'],['明确不纳入','Gluroo 闭环、剂量计算，以及基于图表直接给出用药调整建议的能力。']]),content:`<div class="eyebrow">候选模块 · DRAGGABLE CANDIDATES</div><h2 class="title">把想法放进来，再决定做不做</h2><p class="subtitle">这里故意保留“可选”，避免把竞品能力误读成糖哨兵一期承诺。</p><div class="candidate-board">${[['P1 · 分析','多日曲线叠加','不同日期用不同颜色，观察相似时段反复波动。'],['P1 · 分析','AGP 图谱','展示中位线、25–75% 和 10–90% 区间。'],['P1 · 分析','夜间分析','独立呈现夜间目标范围内时间和异常次数。'],['P1 · 指标','CV / GMI','更适合 7/14 天或更长周期。'],['P1.5 · 报告','基础血糖周报','面向照护沟通的周期摘要。'],['P2 · 家庭照护','异常摘要','用易懂语言提示需要关注的时间段。'],['P2 · 事件关联','饮食/运动/胰岛素关联','事件由糖哨兵 App 记录，再按时间窗叠加。'],['P2 · 智能解释','家庭成员易懂解释','需要事件记录、解释规则和风险话术。'],['明确排除','闭环与剂量计算','Gluroo 相关闭环和剂量计算不进入一期。']].map(x=>`<div class="module"><small>${x[0]}</small><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}</div>`}
};
const dayStats=stats(series.day);
const realtimeStats=stats(series.realtime);
const metricStat=(value,label)=>`<div class="stat"><b>${value}</b><span>${label}</span></div>`;
const dayMetricsMarkup=()=>`<div class="phone-card"><div class="card-title">当天表现 <small>ⓘ</small></div><div class="stat-grid">${metricStat(dayStats.tir+'%','TIR · 目标范围内')}${metricStat(dayStats.tar+'%','TAR · 高于目标')}${metricStat(dayStats.tbr+'%','TBR · 低于目标')}</div><div class="stat-grid" style="margin-top:8px">${metricStat(dayStats.avg,'平均血糖')}${metricStat(dayStats.max,'最高 · 13:20')}${metricStat(dayStats.min,'最低 · 03:45')}</div><div class="stat-grid" style="margin-top:8px">${metricStat(dayStats.range,'最大波动')}</div></div>`;
const trendMetricGrid=(m)=>`${metricStat(m.summary.tir+'%','TIR · 目标范围内')}${metricStat(m.summary.tar+'%','TAR · 高于目标')}${metricStat(m.summary.tbr+'%','TBR · 低于目标')}${metricStat(m.summary.avg,'平均血糖')}${metricStat(m.summary.days,'有效天数')}`;
const trendSummaryMarkup=(m)=>`<div class="phone-card trend-cycle-summary"><div class="card-title">周期摘要</div><div class="stat-grid trend-summary-grid">${trendMetricGrid(m)}</div></div>`;
screens.realtime.content=screens.realtime.content.replace('92%',''+realtimeStats.tir+'%').replace('高低事件','异常时段');
screens.trend.notes=note('页面逻辑','多日趋势是单日分析的上一级入口。默认近 14 天，照护者可以切到近 7 天或自定义；点击某一天进入同一套单日分析页面。',[['本版展示','每日平均血糖、每日最大波动和多日曲线叠加分别表达三种含义；覆盖天数、延迟和数据不足状态独立展示。'],['AGP 数据口径','AGP 当前使用示意数据，手机内以“有效数据 14 天”标识对应周期；正式实现时由该周期的多日血糖数据计算分位区间。'],['家庭照护价值','突出“连续几天在同一时段偏高/偏低”的可发现性。'],['时间范围','先保留自定义入口，默认不增加更多固定按钮。']]);
screens.analysis.content=screens.analysis.content.replace('林小满 · 数据覆盖 23 小时 40 分 · 点击曲线区域查看时间和值','林小满 · 数据覆盖 23 小时 40 分');
screens.analysis.content=screens.analysis.content.replace('<div class="card-title">单日血糖曲线 <small>示意数据</small></div>','<div class="card-title">单日血糖曲线</div>').replace('<div class="coverage"><span>00:00　　06:00　　12:00　　18:00　　24:00</span><b>有效覆盖 23 小时 40 分</b></div>','<div class="coverage only-value"><b>有效覆盖 23 小时 40 分</b></div>');
screens.trend.content=screens.trend.content.replace('<p class="subtitle">观察问题是偶发，还是在相似时段重复发生。</p>','<p class="subtitle">观察问题是偶发，还是在相似时段重复发生。</p>').replace('<small>当天最高值 − 最低值</small>','');
screens.analysis.content=screens.analysis.content.replace(/<div class="phone-card"><div class="card-title">当天表现[\s\S]*?<\/div><div class="phone-card"><div class="card-title">已记录事件/,dayMetricsMarkup()+'<div class="phone-card"><div class="card-title">已记录事件');
screens.trend.content=screens.trend.content.replace(/<div class="phone-card trend-cycle-summary">[\s\S]*?<\/div><div class="phone-card">/,trendSummaryMarkup(averageRanges['14'])+'<div class="phone-card">');
// 多日曲线叠加只作为候选模块，避免默认页面与拖入模块重复展示。
const catalog={'多日曲线叠加':'不同日期用不同颜色，观察相似时段反复波动。','AGP 图谱':'展示中位线、25–75% 和 10–90% 区间。','夜间分析':'独立呈现夜间目标范围内时间和异常次数。','CV / GMI':'更适合 7/14 天或更长周期。','基础血糖周报':'面向照护沟通的周期摘要。','异常摘要':'用易懂语言提示需要关注的时间段。','饮食/运动/胰岛素关联':'将糖哨兵 App 记录的事件按时间窗叠加到曲线。','家庭成员易懂解释':'需要事件记录、解释规则和风险话术共同评审。'};
const dropped={realtime:[],analysis:[],trend:[]},defaults={realtime:['最近血糖曲线','今日摘要'],analysis:['单日血糖曲线','当天表现'],trend:['周期摘要','每日平均血糖']},hidden={realtime:[],analysis:[],trend:[]};
function chrome(key){const title=key==='realtime'?'血糖监测':key==='trend'?'血糖数据':'单日分析',back=key==='analysis'?'<button class="mobile-back" aria-label="返回">‹</button>':'<span class="mobile-back-placeholder"></span>';return `<div class="mobile-topbar">${back}<b>${title}</b><span class="mobile-more">···</span></div>`}
function bottom(key){const active=key==='realtime'?'monitor':key==='analysis'||key==='trend'?'data':'';return `<div class="mobile-bottom-nav"><button class="mobile-tab ${active==='monitor'?'active':''}" data-bottom="monitor"><span>⌁</span>监测</button><button class="mobile-tab ${active==='data'?'active':''}" data-bottom="data"><span>▥</span>数据</button><button class="mobile-tab" data-bottom="device"><span>▣</span>设备</button><button class="mobile-tab" data-bottom="me"><span>♙</span>我的</button></div>`}
function moduleMarkup(name){if(name==='多日曲线叠加')return `<div class="phone-card added-page-module"><div class="card-title">多日曲线叠加</div>${multiDayOverlay()}</div>`;if(name==='AGP 图谱')return `<div class="phone-card added-page-module"><div class="card-title">AGP 图谱</div>${agpMarkup()}</div>`;if(name==='夜间分析')return `<div class="phone-card added-page-module"><div class="card-title">夜间分析</div><div class="night-window">22:00–06:00</div><div class="stat-grid"><div class="stat"><b>91%</b><span>夜间目标范围内时间</span></div><div class="stat"><b>1</b><span>低血糖时段</span></div><div class="stat"><b>5.2</b><span>夜间平均血糖</span></div></div></div>`;if(name==='CV / GMI')return `<div class="phone-card added-page-module"><div class="card-title">CV / GMI</div><div class="stat-grid"><div class="stat"><b>28%</b><span>变异系数 CV</span></div><div class="stat"><b>6.2%</b><span>估算糖化水平 GMI</span></div><div class="stat"><b>14</b><span>有效天数</span></div></div></div>`;if(name==='饮食/运动/胰岛素关联')return `<div class="phone-card added-page-module"><div class="card-title">事件关联</div><div class="event-row"><span>🍽 晚餐</span><b>餐后 2 小时 7.8</b></div><div class="event-row"><span>🏃 运动</span><b>暂无已记录事件</b></div></div>`;return `<div class="phone-card added-page-module"><div class="card-title">${name}</div><p class="module-caption">${catalog[name]}</p></div>`}
const agpMarkup=()=>`<div class="agp-distribution" role="img" aria-label="有效数据 14 天的 AGP 血糖分布图"><svg viewBox="0 0 340 178" class="agp-svg"><rect x="20" y="50" width="310" height="50" rx="3" fill="#e4f8ed"/><line class="grid" x1="20" y1="18" x2="330" y2="18"/><line class="grid" x1="20" y1="50" x2="330" y2="50"/><line class="grid" x1="20" y1="75" x2="330" y2="75"/><line class="grid" x1="20" y1="100" x2="330" y2="100"/><line class="grid" x1="20" y1="132" x2="330" y2="132"/><path d="M20 84 C50 66 80 86 110 72 S165 86 200 64 S255 88 290 70 S315 78 330 66 L330 120 C310 122 295 111 275 117 S230 124 200 112 S155 121 120 108 S70 122 20 106 Z" fill="#c7e9f2" opacity=".82"/><path d="M20 88 C50 76 80 90 110 80 S165 92 200 74 S255 96 290 81 S315 89 330 77 L330 110 C310 112 295 103 275 108 S230 114 200 103 S155 112 120 100 S70 113 20 101 Z" fill="#74c7d8" opacity=".62"/><path d="M20 94 C50 82 80 96 110 86 S165 99 200 86 S255 103 290 90 S315 98 330 88" fill="none" stroke="#126c86" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round"/><text x="1" y="22">14</text><text x="1" y="54">10</text><text x="1" y="79">7</text><text x="1" y="104">3.9</text><text x="7" y="136">0</text><text x="2" y="16" class="unit-label">mmol/L</text><text x="20" y="148">00:00</text><text x="95" y="148">06:00</text><text x="173" y="148">12:00</text><text x="250" y="148">18:00</text><text x="307" y="148">24:00</text></svg><div class="chart-legend agp-legend"><span><i style="width:14px;height:8px;border-radius:2px;background:#e4f8ed;display:inline-block"></i>目标范围</span><span><i style="width:14px;height:8px;border-radius:2px;background:#74c7d8;display:inline-block"></i>25–75% 区间</span><span><i style="width:14px;height:8px;border-radius:2px;background:#c7e9f2;display:inline-block"></i>10–90% 区间</span><span><i style="width:14px;height:3px;border-radius:2px;background:#126c86;display:inline-block"></i>50% 中位线</span></div><div class="coverage"><span>有效数据 14 天</span><b>mmol/L</b></div></div>`;
function content(key,html){let out=html,mods=dropped[key]||[];if(mods.length){const p=mods.map(moduleMarkup).join(''),i=out.lastIndexOf('</div>');out=out.slice(0,i)+p+out.slice(i)}const s=out.indexOf('<div class="phone">');if(s<0)return out;const e=s+'<div class="phone">'.length,c=out.lastIndexOf('</div>');return out.slice(0,e)+chrome(key)+out.slice(e,c)+bottom(key)+out.slice(c)}
function zone(key){const chips=Object.keys(catalog).map(n=>`<button class="candidate-chip" draggable="true" data-module="${n}">${n}</button>`).join(''),ds=defaults[key].map((n,i)=>`<button class="default-chip ${hidden[key].includes(i)?'is-hidden':''}" data-default-index="${i}">${hidden[key].includes(i)?'恢复 ':'隐藏 '}${n}</button>`).join('');return `<section class="drop-zone" data-drop-target="${key}"><h3>页面组合调整</h3><p>候选模块可拖入；默认模块也可以隐藏或恢复，方便评审不同组合效果。</p><div class="default-controls"><span>默认模块：</span>${ds}</div><div class="candidate-tray">${chips}</div><div class="drop-hint">当前页面：${key==='realtime'?'实时监测':key==='analysis'?'单日分析':'多日分析'}</div><div class="dropped-list">${dropped[key].map((n,i)=>`<article class="dropped-module"><button class="remove-module" data-remove="${i}">×</button><b>${n}</b><p>${catalog[n]}</p></article>`).join('')}</div></section>`}
function bindTrendRange(){const root=document.querySelector('.phone');if(!root)return;const summary=root.querySelector('.trend-range-summary'),cycle=root.querySelector('.trend-cycle-summary'),average=root.querySelector('.daily-average-block'),volatility=root.querySelector('.daily-volatility-block');root.querySelectorAll('[data-range]').forEach(btn=>btn.onclick=()=>{const key=rangeKey(btn.dataset.range),m=averageRanges[key];root.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('active',b===btn));if(summary)summary.innerHTML=`<span>${m.label}</span><b>${m.valid}</b>`;if(average)average.outerHTML=multiDayChart(key);if(volatility)volatility.outerHTML=`<div class="daily-volatility-block">${dailyBars(key)}</div>`;if(cycle)cycle.querySelector('.stat-grid').innerHTML=trendMetricGrid(m);bindTrendRange()})}
function render(key='overview'){const s=screens[key];document.querySelector('#canvas').innerHTML=content(key,s.content);document.querySelector('#notes').innerHTML=`<h2>${s.notes.title}</h2><div class="decision">${s.notes.body}</div>${s.notes.sections.map(x=>`<h3>${x[0]}</h3><p>${x[1]}</p>`).join('')}`;document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.screen===key);b.onclick=()=>render(b.dataset.screen)});if(['realtime','analysis','trend'].includes(key)){document.querySelectorAll('.phone .phone-card').forEach((c,i)=>c.classList.toggle('default-hidden',hidden[key].includes(i)));document.querySelector('#canvas').insertAdjacentHTML('beforeend',zone(key));const z=document.querySelector(`[data-drop-target="${key}"]`),add=n=>{if(catalog[n]&&!dropped[key].includes(n)){dropped[key].push(n);render(key)}};z.ondragover=e=>{e.preventDefault();z.classList.add('over')};z.ondragleave=()=>z.classList.remove('over');z.ondrop=e=>{e.preventDefault();z.classList.remove('over');add(e.dataTransfer.getData('text/plain'))};z.querySelectorAll('.candidate-chip').forEach(b=>{b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.module);b.onclick=()=>add(b.dataset.module)});z.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{dropped[key].splice(+b.dataset.remove,1);render(key)});z.querySelectorAll('.default-chip').forEach(b=>b.onclick=()=>{const i=+b.dataset.defaultIndex;hidden[key]=hidden[key].includes(i)?hidden[key].filter(x=>x!==i):[...hidden[key],i];render(key)});document.querySelector('.mobile-back')?.addEventListener('click',()=>render('trend'));document.querySelectorAll('.mobile-tab').forEach(b=>b.onclick=()=>{if(b.dataset.bottom==='monitor')render('realtime');if(b.dataset.bottom==='data')render('trend')})};if(key==='trend')bindTrendRange()}
screens.analysis.content=screens.analysis.content.replace('<div class="card-title">单日血糖曲线 <small>示意数据</small></div>','<div class="card-title">单日血糖曲线</div>').replace('<div class="coverage"><span>00:00　　06:00　　12:00　　18:00　　24:00</span><b>有效覆盖 23 小时 40 分</b></div>','<div class="coverage only-value"><b>有效覆盖 23 小时 40 分</b></div>');
screens.overview.content=screens.overview.content.replace('<li>AGP、CV、GMI</li>','<li>CV、GMI</li>').replace('<li>覆盖天数、延迟、中断、数据不足</li>','<li>覆盖天数、延迟、中断、数据不足</li><li>AGP 图谱（多日分析核心模块）</li>');
defaults.trend=['周期摘要','AGP 图谱','每日平均血糖','每日最大波动'];
screens.analysis.content=screens.analysis.content.replace(/<div class="phone-card"><div class="card-title">已记录事件[\s\S]*?<\/div><\/div>(?=<\/div>$)/,'');
screens.analysis.notes.sections[2]=['P0 边界','本页只呈现血糖曲线、目标范围、核心指标和异常时段，不包含事件记录入口、事件空状态或行为事件标记。'];
screens.candidates.notes.sections[0][1]=screens.candidates.notes.sections[0][1].replace('、AGP','');
const originalModuleMarkup=moduleMarkup;
moduleMarkup=(name)=>name==='饮食/运动/胰岛素关联'?'<div class="phone-card added-page-module"><div class="card-title">事件关联</div><p class="module-caption">后续能力：仅在糖哨兵 App 存在真实记录后展示时间关联，不输出因果结论或用药建议。</p></div>':originalModuleMarkup(name);
const agpCardMarkup=()=>`<div class="phone-card agp-card"><div class="card-title">AGP 图谱</div>${agpMarkup()}<div class="agp-unavailable" hidden>AGP 暂不可用：当前周期有效数据不足，暂不展示分布图谱。</div></div>`;
screens.trend.content=screens.trend.content.replace('<div class="phone-card"><div class="card-title">每日平均血糖',agpCardMarkup()+'<div class="phone-card"><div class="card-title">每日平均血糖');
delete catalog['AGP 图谱'];
screens.candidates.content=screens.candidates.content.replace('<div class="module"><small>P1 · 分析</small><b>AGP 图谱</b><p>展示中位线、25–75% 和 10–90% 区间。</p></div>','');
screens.candidates.content=screens.candidates.content.replace('P2 · 智能解释','后续待评估').replace('家庭成员易懂解释','照护摘要');
// P0 单一当前使用者：家庭照护是场景背景，不在本期实现多照护对象或对象切换。
const singleCurrentUser=(html)=>html
  .replaceAll('林小满的血糖','我的血糖')
  .replaceAll('林小满 <small>⌄</small>','我的血糖')
  .replaceAll('林小满 · 外部 CGM','外部 CGM')
  .replaceAll('林小满 · 数据覆盖','当前使用者 · 数据覆盖')
  .replaceAll('默认照护对象','单一当前使用者')
  .replaceAll('高低事件','异常提醒')
  .replaceAll('家庭成员易懂解释','照护摘要');
screens.overview.notes.sections[0][1]='本期按单一当前使用者展示，查看当前状态与连续血糖变化；多照护对象和对象切换时机待后续产品决策。';
screens.realtime.title='血糖 Tab｜实时监测';
screens.realtime.sub='P0 · 单一当前使用者的第一眼状态查看';
screens.realtime.content=singleCurrentUser(screens.realtime.content);
screens.realtime.notes=note('页面逻辑','按单一当前使用者展示；当前值、趋势箭头、更新时间和状态必须同一数据快照生成。',[['时间选择决策','本版采用 6/12/24 小时。3/6/12/24（硅基）、4/8/12/24（三诺）、6/12/24（微泰）、4/12/24（糖动）作为竞品参考，不直接照搬。'],['状态','目标范围内、偏高、偏低、数据延迟、数据中断。'],['事件边界','P0 不包含事件记录入口、事件空状态或行为事件标记。']]);
screens.analysis.content=singleCurrentUser(screens.analysis.content);
screens.trend.notes.sections[2]=['单一使用者价值','从同一使用者的连续日期中归纳相似时段的重复波动，先判断问题是否持续，再下钻到具体某一天。'];
const renderPrototype=render;
render=(key='overview')=>{renderPrototype(key);if(key==='candidates')document.querySelectorAll('.module').forEach(x=>{if(x.querySelector('b')?.textContent.trim()==='AGP 图谱')x.remove()});if(key==='trend'){const root=document.querySelector('.phone'),first=root?.querySelector('.phone-card'),cycle=root?.querySelector('.trend-cycle-summary'),avg=root?.querySelector('.daily-average-block');if(root&&first&&cycle&&!root.querySelector('.agp-card')){const avgCard=document.createElement('div');avgCard.className='phone-card';if(avg)avgCard.append(avg);first.after(cycle);cycle.insertAdjacentHTML('afterend',agpCardMarkup());const agpCard=root.querySelector('.agp-card');if(agpCard)agpCard.after(avgCard)}const agp=root?.querySelector('.agp-distribution'),empty=root?.querySelector('.agp-unavailable');if(agp&&empty){const update=()=>{const m=averageRanges[rangeKey(root.querySelector('[data-range].active')?.dataset.range||'14')],days=Number(String(m.summary.days).split('/')[0]),ok=days>=5;agp.hidden=!ok;empty.hidden=ok;if(ok)agp.querySelector('.coverage span').textContent=`有效数据 ${days} 天`;};root.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',()=>setTimeout(update,0)));update()}}};
render();
